### PR TITLE
Dev 0.7.0

### PR DESCRIPTION
**Pull request by matinnuhamunada**
Resolves:
- [x] handling large samples (fix shell input too long errors) #251 #229
- [x] Improve wiki and documentation: https://github.com/NBChub/bgcflow/wiki
- [x] Refrain using git clone #242

New features/updates:
- [x] antiSMASH 7
- [x] GTDB R214
- [x] Use the latest BiG-SLICE update from https://github.com/medema-group/bigslice/commit/103d8f2d0ca5d1a26a35328a9a20eb0b691d4d96. **WARNING:** The original `download_bigslice_hmmdb` does not work, so a workaround is required to set it up. This is a temporary fix until a stable release of BiG-SLICE is out. See https://github.com/NBChub/bgcflow/pull/254/commits/ecb0716321cc6d5939b0aadead9b4252f6a71bbd for details
- [x] Clearly add information on how to choose antiSMASH/ GTDB versions in the main documentation. I think it's quite important for new users. See: https://github.com/NBChub/bgcflow/wiki/Advanced-Configurations

Changes:
- [x] move log dir to root
- [x] enable `pipeline` as an alias to `rules`
- [x] enable `pep` as an alias to `name`
- [ ] ~~#180~~
- [ ] #219
- [ ] ~~#209~~
- [ ] ~~Enable using input from annotated `.gbk` files~~
- [ ] ~~Enable using input from previous antismash run~~

### CODE REVIEW

**Comment by OmkarSaMo** [comment]
@matinnuhamunada : Regarding the GTDB-Tk. Do we want to utilize the new ani_screen step? I see that you have currently chosen to skip this step. I think it could be valuable to add this step. We just need to add the Mash DB sketch location at resources directory.

**Comment by matinnuhamunada** [comment]
> @matinnuhamunada : Regarding the GTDB-Tk. Do we want to utilize the new ani_screen step? I see that you have currently chosen to skip this step. I think it could be valuable to add this step. We just need to add the Mash DB sketch location at resources directory.

Does it improve the speed? I throws me an error before, but probably because I haven't figure out the mash db sketch thing

**Comment by matinnuhamunada** [comment]
@OmkarSaMo I fixed the `ani_screen`. I think it is fine to merge into the main branch and create a pre-release featuring antiSMASH7, then work on the other features in 0.7.1. I don't think I can get much done until after the summer break.

**Comment by matinnuhamunada** [comment]
> @OmkarSaMo I fixed the `ani_screen`. I think it is fine to merge into the main branch and create a pre-release featuring antiSMASH7, then work on the other features in 0.7.1. I don't think I can get much done until after the summer break.
> 
> I think we need to start moving the bit from README to the WIKI https://github.com/NBChub/bgcflow/wiki

Actually, turning the ani_screen takes ~20 hours to finish for 33 genomes that are not in NCBI. I guess we should disable the feature as a default, but gives configuration to turn it on.

**Comment by OmkarSaMo** [comment]
> turn

It did take me a very long time to run with this feature on 1300 genomes : 64 CPUs over 70 hours. I just thought initially that this feature would be highly valuable. But I am not sure anymore as it slowed down the process too much. I like your idea to keep this as an option.

**Review by OmkarSaMo — APPROVED** [review]

**Comment by OmkarSaMo** [comment]
> @OmkarSaMo I fixed the `ani_screen`. I think it is fine to merge into the main branch and create a pre-release featuring antiSMASH7, then work on the other features in 0.7.1. I don't think I can get much done until after the summer break.
> 
> I think we need to start moving the bit from README to the WIKI https://github.com/NBChub/bgcflow/wiki

Agreed.

**Pull request merged**
